# Navigation Links

main:
  - name: Home
    url: /
    weight: 10

  - name: Team
    weight: 20
    hasChildren: true

  - parent: Team
    name: Professor
    url: /team/professor/
    weight: 21

  - parent: Team
    name: Researchers
    url: /team/researchers/
    weight: 22

  - name: Research
    url: /research/
    weight: 30

  - name: Publications
    weight: 40
    hasChildren: true

  - parent: Publications
    name: Journal
    url: /publications/journal/
    weight: 41

  - parent: Publications
    name: Patent
    url: /publications/patent/
    weight: 42

  - parent: Publications
    name: Conference
    url: /publications/conference/
    weight: 43

  - name: Teaching
    url: /teaching/
    weight: 50

  - name: Sponsors
    url: /sponsors/
    weight: 60

  - name: Board
    weight: 70
    hasChildren: true

  - parent: Board
    name: News
    url: /board/news/
    weight: 71

  - parent: Board
    name: Gallery
    url: /board/gallery/
    weight: 72

  - name: Contact
    url: /contact/
    weight: 80

  - name: Join MFL
    url: /join/
    weight: 90
